### ISSUE TITLE
Project is not building

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit#221]
The project has not being built for a while due to an issue with G1 logs.

https://github.com/microsoft/gctoolkit/actions/workflows/maven.yml

@kcpeppe @dsgrieve any idea?

**Comment by karianna** [comment]
[INFO] Running com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest
[ERROR] com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest.unifiedLog  Time elapsed: 0.037 s  <<< ERROR!
java.lang.RuntimeException: unified/g1gc/gc-all-info.log.zip not found
	at com.microsoft.gctoolkit.integration@2.0.11-SNAPSHOT/com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest.logTest(SingleGarbageCollectionLogFileTest.java:22)
	at com.microsoft.gctoolkit.integration@2.0.11-SNAPSHOT/com.microsoft.gctoolkit.integration.io.SingleGarbageCollectionLogFileTest.unifiedLog(SingleGarbageCollectionLogFileTest.java:61)
